import * as fs from "fs";
import * as path from "path";
import { GoogleGenAI, Modality } from "@google/genai";

// DON'T DELETE THIS COMMENT
// Follow these instructions when using this blueprint:
// - Note that the newest Gemini model series is "gemini-2.5-flash" or "gemini-2.5-pro"
//   - do not change this unless explicitly requested by the user

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export async function generateTryOnImage(
  userPhotoPath: string,
  clothingImagePath: string,
  outputPath: string
): Promise<string> {
  try {
    // Read both images
    const userPhotoBytes = fs.readFileSync(userPhotoPath);
    const clothingImageBytes = fs.readFileSync(clothingImagePath);

    const userPhotoMime = userPhotoPath.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';
    const clothingMime = clothingImagePath.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';

    const prompt = `You are a virtual try-on AI. Generate a realistic image of the person in the first photo wearing the clothing item shown in the second photo. 
    
    Rules:
    1. Keep the person's face, body shape, and pose exactly the same
    2. Replace their current top/outfit with the clothing item shown
    3. Make the clothing fit naturally on their body
    4. Maintain realistic lighting and shadows
    5. Keep the background the same
    6. The result should look like a professional fashion photo
    
    Generate the try-on image now.`;

    // IMPORTANT: only this gemini model supports image generation
    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash-preview-image-generation",
      contents: [
        {
          role: "user",
          parts: [
            {
              inlineData: {
                data: userPhotoBytes.toString("base64"),
                mimeType: userPhotoMime,
              },
            },
            {
              inlineData: {
                data: clothingImageBytes.toString("base64"),
                mimeType: clothingMime,
              },
            },
            { text: prompt },
          ],
        },
      ],
      config: {
        responseModalities: [Modality.TEXT, Modality.IMAGE],
      },
    });

    const candidates = response.candidates;
    if (!candidates || candidates.length === 0) {
      throw new Error("No response from AI model");
    }

    const content = candidates[0].content;
    if (!content || !content.parts) {
      throw new Error("Invalid response structure from AI model");
    }

    for (const part of content.parts) {
      if (part.inlineData && part.inlineData.data) {
        const imageData = Buffer.from(part.inlineData.data, "base64");
        
        // Ensure output directory exists
        const outputDir = path.dirname(outputPath);
        if (!fs.existsSync(outputDir)) {
          fs.mkdirSync(outputDir, { recursive: true });
        }
        
        fs.writeFileSync(outputPath, imageData);
        return outputPath;
      }
    }

    throw new Error("No image generated by AI model");
  } catch (error) {
    console.error("Failed to generate try-on image:", error);
    throw new Error(`Failed to generate try-on image: ${error}`);
  }
}

export async function analyzeClothingImage(imagePath: string): Promise<{
  category: string;
  description: string;
}> {
  try {
    const imageBytes = fs.readFileSync(imagePath);
    const mimeType = imagePath.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: "object",
          properties: {
            category: { 
              type: "string",
              enum: ["shirts", "pants", "jackets", "dresses", "skirts", "accessories", "shoes", "other"]
            },
            description: { type: "string" },
          },
          required: ["category", "description"],
        },
      },
      contents: [
        {
          role: "user",
          parts: [
            {
              inlineData: {
                data: imageBytes.toString("base64"),
                mimeType,
              },
            },
            {
              text: "Analyze this clothing item. Determine its category (shirts, pants, jackets, dresses, skirts, accessories, shoes, or other) and provide a brief description.",
            },
          ],
        },
      ],
    });

    const rawJson = response.text;
    if (rawJson) {
      return JSON.parse(rawJson);
    }
    
    return { category: "other", description: "Clothing item" };
  } catch (error) {
    console.error("Failed to analyze clothing image:", error);
    return { category: "other", description: "Clothing item" };
  }
}
