import { sql, relations } from "drizzle-orm";
import { pgTable, text, varchar, integer, boolean, timestamp, pgEnum } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Enums
export const userRoleEnum = pgEnum("user_role", ["company_owner", "store_manager", "customer"]);
export const clothingCategoryEnum = pgEnum("clothing_category", ["shirts", "pants", "jackets", "dresses", "skirts", "accessories", "shoes", "other"]);

// Users table - Company owners and store managers
export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  role: userRoleEnum("role").notNull().default("store_manager"),
  storeId: varchar("store_id").references(() => stores.id),
  mustResetPassword: boolean("must_reset_password").default(true),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// Stores table
export const stores = pgTable("stores", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  description: text("description"),
  logoUrl: text("logo_url"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// Clothing items table
export const clothingItems = pgTable("clothing_items", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  storeId: varchar("store_id").notNull().references(() => stores.id),
  name: text("name").notNull(),
  imageUrl: text("image_url").notNull(),
  category: clothingCategoryEnum("category").notNull(),
  barcode: text("barcode"),
  isAvailable: boolean("is_available").default(true),
  tryOnCount: integer("try_on_count").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// QR Sessions - Generated by store managers for customer access
export const qrSessions = pgTable("qr_sessions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  storeId: varchar("store_id").notNull().references(() => stores.id),
  token: text("token").notNull().unique(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

// Customer sessions - Created when customer scans QR
export const customerSessions = pgTable("customer_sessions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  qrSessionId: varchar("qr_session_id").notNull().references(() => qrSessions.id),
  storeId: varchar("store_id").notNull().references(() => stores.id),
  photoUrl: text("photo_url"),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

// Try-on history - Records of AI generations
export const tryOnHistory = pgTable("try_on_history", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  customerSessionId: varchar("customer_session_id").notNull().references(() => customerSessions.id),
  clothingItemId: varchar("clothing_item_id").notNull().references(() => clothingItems.id),
  resultImageUrl: text("result_image_url"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Usage logs for analytics
export const usageLogs = pgTable("usage_logs", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  storeId: varchar("store_id").notNull().references(() => stores.id),
  action: text("action").notNull(), // 'try_on', 'clothing_upload', 'session_created', 'qr_generated'
  metadata: text("metadata"), // JSON string for additional data
  createdAt: timestamp("created_at").defaultNow(),
});

// Relations
export const usersRelations = relations(users, ({ one }) => ({
  store: one(stores, {
    fields: [users.storeId],
    references: [stores.id],
  }),
}));

export const storesRelations = relations(stores, ({ many }) => ({
  users: many(users),
  clothingItems: many(clothingItems),
  qrSessions: many(qrSessions),
  customerSessions: many(customerSessions),
  usageLogs: many(usageLogs),
}));

export const clothingItemsRelations = relations(clothingItems, ({ one, many }) => ({
  store: one(stores, {
    fields: [clothingItems.storeId],
    references: [stores.id],
  }),
  tryOnHistory: many(tryOnHistory),
}));

export const qrSessionsRelations = relations(qrSessions, ({ one, many }) => ({
  store: one(stores, {
    fields: [qrSessions.storeId],
    references: [stores.id],
  }),
  customerSessions: many(customerSessions),
}));

export const customerSessionsRelations = relations(customerSessions, ({ one, many }) => ({
  qrSession: one(qrSessions, {
    fields: [customerSessions.qrSessionId],
    references: [qrSessions.id],
  }),
  store: one(stores, {
    fields: [customerSessions.storeId],
    references: [stores.id],
  }),
  tryOnHistory: many(tryOnHistory),
}));

export const tryOnHistoryRelations = relations(tryOnHistory, ({ one }) => ({
  customerSession: one(customerSessions, {
    fields: [tryOnHistory.customerSessionId],
    references: [customerSessions.id],
  }),
  clothingItem: one(clothingItems, {
    fields: [tryOnHistory.clothingItemId],
    references: [clothingItems.id],
  }),
}));

export const usageLogsRelations = relations(usageLogs, ({ one }) => ({
  store: one(stores, {
    fields: [usageLogs.storeId],
    references: [stores.id],
  }),
}));

// Insert schemas
export const insertUserSchema = createInsertSchema(users).omit({ id: true, createdAt: true });
export const insertStoreSchema = createInsertSchema(stores).omit({ id: true, createdAt: true });
export const insertClothingItemSchema = createInsertSchema(clothingItems).omit({ id: true, createdAt: true, updatedAt: true, tryOnCount: true });
export const insertQrSessionSchema = createInsertSchema(qrSessions).omit({ id: true, createdAt: true });
export const insertCustomerSessionSchema = createInsertSchema(customerSessions).omit({ id: true, createdAt: true });
export const insertTryOnHistorySchema = createInsertSchema(tryOnHistory).omit({ id: true, createdAt: true });
export const insertUsageLogSchema = createInsertSchema(usageLogs).omit({ id: true, createdAt: true });

// Types
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type InsertStore = z.infer<typeof insertStoreSchema>;
export type Store = typeof stores.$inferSelect;
export type InsertClothingItem = z.infer<typeof insertClothingItemSchema>;
export type ClothingItem = typeof clothingItems.$inferSelect;
export type InsertQrSession = z.infer<typeof insertQrSessionSchema>;
export type QrSession = typeof qrSessions.$inferSelect;
export type InsertCustomerSession = z.infer<typeof insertCustomerSessionSchema>;
export type CustomerSession = typeof customerSessions.$inferSelect;
export type InsertTryOnHistory = z.infer<typeof insertTryOnHistorySchema>;
export type TryOnHistory = typeof tryOnHistory.$inferSelect;
export type InsertUsageLog = z.infer<typeof insertUsageLogSchema>;
export type UsageLog = typeof usageLogs.$inferSelect;

// Login schema
export const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
});

export type LoginInput = z.infer<typeof loginSchema>;

// Create store manager schema
export const createStoreManagerSchema = z.object({
  email: z.string().email(),
  storeName: z.string().min(1),
  storeDescription: z.string().optional(),
});

export type CreateStoreManagerInput = z.infer<typeof createStoreManagerSchema>;

// Reset password schema
export const resetPasswordSchema = z.object({
  currentPassword: z.string().min(6),
  newPassword: z.string().min(6),
});

export type ResetPasswordInput = z.infer<typeof resetPasswordSchema>;

// Clothing category type
export type ClothingCategory = "shirts" | "pants" | "jackets" | "dresses" | "skirts" | "accessories" | "shoes" | "other";
export const clothingCategories: ClothingCategory[] = ["shirts", "pants", "jackets", "dresses", "skirts", "accessories", "shoes", "other"];
